from __future__ import annotations

import argparse
import csv
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

from ollama_client import OllamaClient


SYSTEM_PROMPT = """You are assisting an academic AI-video project.

Your task is prompt iteration after human review. The user provides problem
records and optimization directions after reviewing generated image/video
outputs. Use those notes to identify concrete prompt changes.

Integrity rules:
- Do not invent new scenes, assets, characters, generated clips, or platform actions.
- Preserve shot IDs and story order.
- Treat human feedback as the source of truth for the new iteration.
- Keep the output focused on prompt changes, continuity risks, and manual review notes.
- Do not claim that image or video files were regenerated by this script.
"""

SHOT_ID_RE = re.compile(r"\b(?:s\d+(?:-\d+)?|s4|global)\b", re.IGNORECASE)


@dataclass
class FeedbackDocument:
    path: Path
    text: str
    shot_ids: set[str]


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8").strip()


def discover_feedback(feedback_dir: Path) -> list[FeedbackDocument]:
    if not feedback_dir.exists():
        raise FileNotFoundError(f"Feedback folder does not exist: {feedback_dir}")
    files = sorted(
        path
        for path in feedback_dir.iterdir()
        if path.is_file() and path.suffix.lower() in {".md", ".txt"} and path.name.lower() != "readme.md"
    )
    if not files:
        raise FileNotFoundError(
            f"No feedback documents found in {feedback_dir}. Add at least one .md or .txt file."
        )

    documents: list[FeedbackDocument] = []
    for path in files:
        text = read_text(path)
        if not text:
            raise ValueError(f"Feedback document is empty: {path}")
        shot_ids = {match.group(0).lower() for match in SHOT_ID_RE.finditer(text)}
        documents.append(FeedbackDocument(path=path, text=text, shot_ids=shot_ids))
    return documents


def read_prompt_table(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        raise FileNotFoundError(f"Prompt table does not exist: {path}")
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        reader = csv.DictReader(handle)
        rows = [dict(row) for row in reader]
    if not rows:
        raise ValueError(f"Prompt table is empty: {path}")
    required = {"id", "title", "refined_image_prompt", "refined_video_prompt"}
    missing = required.difference(reader.fieldnames or [])
    if missing:
        raise ValueError(f"Prompt table is missing required columns: {sorted(missing)}")
    return rows


def feedback_for_shot(documents: list[FeedbackDocument], shot_id: str) -> list[FeedbackDocument]:
    shot_id = shot_id.lower()
    matched = [
        document
        for document in documents
        if "global" in document.shot_ids or shot_id in document.shot_ids or not document.shot_ids
    ]
    return matched


def feedback_text(documents: list[FeedbackDocument]) -> str:
    blocks = []
    for document in documents:
        blocks.append(f"Feedback file: {document.path.as_posix()}\n{document.text}")
    return "\n\n---\n\n".join(blocks)


def append_iteration_constraints(prompt: str, documents: list[FeedbackDocument]) -> str:
    if not documents:
        return prompt
    return (
        prompt.strip()
        + "\n\nIteration feedback to address in the next generation attempt:\n"
        + feedback_text(documents)
        + "\n\nRevision instruction:\n"
        + "Revise the next manual upload attempt to address the feedback above while preserving the existing story, declared assets, shot ID, and visual continuity."
    )


def build_next_round_rows(rows: list[dict[str, str]], documents: list[FeedbackDocument]) -> list[dict[str, str]]:
    next_rows: list[dict[str, str]] = []
    for row in rows:
        shot_id = row.get("id", "").strip()
        matched = feedback_for_shot(documents, shot_id)
        next_rows.append(
            {
                "id": shot_id,
                "title": row.get("title", ""),
                "tool": row.get("tool", ""),
                "method": row.get("method", ""),
                "previous_refined_image_prompt": row.get("refined_image_prompt", ""),
                "next_image_prompt": append_iteration_constraints(row.get("refined_image_prompt", ""), matched),
                "previous_refined_video_prompt": row.get("refined_video_prompt", ""),
                "next_video_prompt": append_iteration_constraints(row.get("refined_video_prompt", ""), matched),
                "image_path": row.get("image_path", ""),
                "video_path": row.get("video_path", ""),
                "feedback_files": "; ".join(str(document.path).replace("\\", "/") for document in matched),
                "iteration_status": "feedback applied" if matched else "no matching feedback; previous prompt preserved",
            }
        )
    return next_rows


def write_next_round_table(output_path: Path, rows: list[dict[str, str]]) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    fields = [
        "id",
        "title",
        "tool",
        "method",
        "previous_refined_image_prompt",
        "next_image_prompt",
        "previous_refined_video_prompt",
        "next_video_prompt",
        "image_path",
        "video_path",
        "feedback_files",
        "iteration_status",
    ]
    with output_path.open("w", encoding="utf-8-sig", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields)
        writer.writeheader()
        writer.writerows(rows)


def build_analysis_prompt(rows: list[dict[str, str]], documents: list[FeedbackDocument], round_id: str) -> str:
    compact_rows = [
        {
            "id": row.get("id", ""),
            "title": row.get("title", ""),
            "tool": row.get("tool", ""),
            "method": row.get("method", ""),
            "has_image_reference": bool(row.get("image_path")),
            "has_existing_clip": bool(row.get("video_path")),
        }
        for row in rows
    ]
    return (
        "Analyze the human feedback and write a concise iteration report. "
        "Use exactly these sections: Iteration Scope, Shot-Level Problems, Prompt Revision Strategy, Remaining Manual Checks. "
        "Do not invent new assets or claim that media has been regenerated.\n\n"
        f"Round: {round_id}\n"
        f"Shots: {json.dumps(compact_rows, ensure_ascii=False)}\n\n"
        f"Feedback documents:\n{feedback_text(documents)}"
    )


def write_report(output_path: Path, rows: list[dict[str, str]], documents: list[FeedbackDocument], llm_text: str) -> None:
    lines = [
        "# Prompt Iteration Report",
        "",
        "## Input Feedback Documents",
        "",
    ]
    for document in documents:
        shot_list = ", ".join(sorted(document.shot_ids)) if document.shot_ids else "global by default"
        lines.append(f"- `{document.path.as_posix()}` -> {shot_list}")

    lines.extend(["", "## Generated Next-Round Prompt Table", "", f"- Rows: {len(rows)}", ""])
    for row in rows:
        lines.extend(
            [
                f"### {row['id']}: {row['title']}",
                "",
                f"- Iteration status: {row['iteration_status']}",
                f"- Feedback files: {row['feedback_files'] or 'none'}",
                "",
            ]
        )
    lines.extend(["## Ollama Iteration Analysis", "", llm_text, ""])
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")


def write_manifest(output_path: Path, round_id: str, rows: list[dict[str, str]], documents: list[FeedbackDocument]) -> None:
    payload: dict[str, Any] = {
        "workflow_stage": "feedback-driven prompt iteration",
        "round_id": round_id,
        "asset_policy": "This stage reads human feedback and writes next-round prompt artifacts only. It does not create, modify, or replace image/video assets.",
        "feedback_documents": [
            {
                "path": document.path.as_posix(),
                "detected_shot_ids": sorted(document.shot_ids),
            }
            for document in documents
        ],
        "shot_count": len(rows),
        "generated_files": [
            f"iterations/{round_id}/next_prompt_table.csv",
            f"iterations/{round_id}/iteration_report.md",
            f"iterations/{round_id}/iteration_manifest.json",
        ],
    }
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate next-round prompts from human problem records.")
    parser.add_argument("--feedback-dir", type=Path, default=Path("data/input/problem_records"))
    parser.add_argument("--prompt-table", type=Path, default=Path("data/output/refined_prompt_table.csv"))
    parser.add_argument("--output-dir", type=Path, default=Path("data/output/iterations"))
    parser.add_argument("--round-id", default="round_01")
    parser.add_argument("--base-url", default="http://localhost:11434")
    parser.add_argument("--model", default="gemma3:1b")
    parser.add_argument("--dry-run", action="store_true", help="Skip Ollama and write deterministic prompt table/report.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    documents = discover_feedback(args.feedback_dir)
    rows = read_prompt_table(args.prompt_table)
    next_rows = build_next_round_rows(rows, documents)
    round_dir = args.output_dir / args.round_id

    if args.dry_run:
        llm_text = "DRY RUN: feedback documents were detected and next-round prompts were written without calling Ollama."
    else:
        client = OllamaClient(args.base_url)
        llm_text = client.generate(
            model=args.model,
            system_prompt=SYSTEM_PROMPT,
            user_prompt=build_analysis_prompt(rows, documents, args.round_id),
            temperature=0.2,
        )

    write_next_round_table(round_dir / "next_prompt_table.csv", next_rows)
    write_report(round_dir / "iteration_report.md", next_rows, documents, llm_text)
    write_manifest(round_dir / "iteration_manifest.json", args.round_id, next_rows, documents)
    print(f"Wrote iteration artifacts to {round_dir.resolve()}")


if __name__ == "__main__":
    main()
